_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 9644096e-f7e7-4b46-a56e-bc5aa7958b6c
name: 'Local Employee Management Portal'
mail: rajdip.roy@innoraft.com
slogan: 'Module 3 exam'
page:
  403: /node/2
  404: /node/1
  front: /node/15
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
